version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: cliente_sistema
      POSTGRES_PASSWORD: misistema
      POSTGRES_DB: my_db
      TZ: America/Bogota
      PGTZ: America/Bogota
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  server2:
    build: .
    container_name: server2
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_NAME: "my_db"
      DB_USER: "cliente_sistema"
      DB_PASSWORD: "misistema"
      PORT: "5002"
    ports:
      - "5002:5002"

volumes:
  db_data:
